# -*- coding: utf-8 -*-
"""BERTNewsClassifier.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wLlbgWHIMHsNThK3_WsMndvnxF4FxCgu

# 🛠️ Install Libraries

This cell installs and updates essential libraries for BERT training. Remember to restart the Colab runtime after running it.
"""

# Clean + compatible install for BERT training (Colab-safe)
!pip uninstall -y transformers accelerate datasets evaluate peft
!pip install -q --upgrade \
  transformers \
  accelerate \
  datasets \
  evaluate \
  peft

# IMPORTANT: Please restart the Colab runtime after running this cell
# (Runtime -> Restart runtime) for the changes to take full effect.

"""This cell imports core libraries like `torch`, `transformers` components (Trainer, AutoTokenizer), `datasets`, and `evaluate`. It then confirms successful imports.

# 📦 Data Loading and Preparation
"""

import torch
from transformers import Trainer, AutoTokenizer
from datasets import load_dataset
import evaluate

print("Torch:", torch.__version__)
print("Transformers import OK")
print("Datasets import OK")
print("Evaluate import OK")

"""This cell loads the `ag_news` dataset, tokenizes it using BERT's tokenizer, and prepares it for training by reformatting columns and setting the PyTorch tensor format."""

from datasets import load_dataset
from transformers import AutoTokenizer

# Load dataset
dataset = load_dataset("ag_news")

# Inspect structure (optional, for verification)
print("Original dataset structure:", dataset)
print("First training example:", dataset["train"][0])

# Initialize tokenizer
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")

def tokenize_function(example):
    return tokenizer(
        example["text"],
        padding="max_length",
        truncation=True,
        max_length=128
    )

tokenized_datasets = dataset.map(tokenize_function, batched=True)

print("First tokenized training example:", tokenized_datasets["train"][0])

# Original content of this cell:
# Remove raw text (not needed anymore)
tokenized_datasets = tokenized_datasets.remove_columns(["text"])

# Rename label → labels (Trainer expects this exact name)
tokenized_datasets = tokenized_datasets.rename_column("label", "labels")

# Set PyTorch format
tokenized_datasets.set_format("torch")

print("Dataset prepared for training ✅")

"""This cell initializes the `Trainer` object, which manages the training process using the model, training arguments, datasets, and a metrics function.

This cell loads the BERT model, defines evaluation metrics (accuracy, f1), sets up training arguments, initializes the Hugging Face `Trainer`, and starts the model training.
"""

from transformers import Trainer

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"].shuffle(seed=42).select(range(10000)),
    eval_dataset=tokenized_datasets["test"].select(range(2000)),
    compute_metrics=compute_metrics
)

print("Trainer ready ✅")

# Ensure 'evaluate' is installed in case of runtime issues
!pip install -q evaluate

from transformers import Trainer, AutoModelForSequenceClassification, TrainingArguments
import evaluate
import numpy as np

# Load model
model = AutoModelForSequenceClassification.from_pretrained(
    "bert-base-uncased",
    num_labels=4
)
print("Model loaded successfully ✅")

# Define compute_metrics function
accuracy = evaluate.load("accuracy")
f1 = evaluate.load("f1")

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)

    return {
        "accuracy": accuracy.compute(predictions=preds, references=labels)["accuracy"],
        "f1": f1.compute(predictions=preds, references=labels, average="weighted")["f1"]
    }

print("Metrics function ready ✅")

# Define TrainingArguments
training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="steps",
    save_strategy="steps",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=2,
    weight_decay=0.01,
    logging_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="accuracy",
    greater_is_better=True,
    fp16=True,
    report_to="none"
)
print("Training arguments set ✅")

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"].shuffle(seed=42).select(range(10000)),
    eval_dataset=tokenized_datasets["test"].select(range(2000)),
    compute_metrics=compute_metrics
)

print("Trainer initialized ✅")

trainer.train()