# -*- coding: utf-8 -*-
"""Context-Aware Chatbot (RAG).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16H7i6-hYLXeqEkmJFFt_fa9XZ8xSi_A1
"""

!pip install -q langchain langchain-community faiss-cpu sentence-transformers

!pip install -q langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

documents = [
    "Machine learning enables systems to learn from data without explicit programming.",
    "Deep learning uses neural networks with many layers for complex pattern recognition.",
    "RAG combines retrieval systems with LLMs to generate context-aware answers.",
    "Vector databases store embeddings for semantic search."
]

print("Documents loaded:", len(documents))

from langchain_text_splitters import RecursiveCharacterTextSplitter
from sentence_transformers import SentenceTransformer
import numpy as np
import faiss

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=100,
    chunk_overlap=20
)

chunks = []
for doc in documents:
    chunks.extend(text_splitter.split_text(doc))

print("Total chunks:", len(chunks))

model = SentenceTransformer("all-MiniLM-L6-v2")

embeddings = model.encode(chunks)

embeddings = np.array(embeddings).astype("float32")

print("Embedding shape:", embeddings.shape)

dimension = embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)
index.add(embeddings)

print("FAISS index built ✅")

import numpy as np

def retrieve(query, k=3):
    # convert query → embedding
    query_vec = model.encode([query]).astype("float32")

    # search nearest neighbors
    distances, indices = index.search(query_vec, k)

    # return top matching chunks
    results = [chunks[i] for i in indices[0]]

    return results

query = "What is retrieval augmented generation?"

results = retrieve(query)

for i, r in enumerate(results):
    print(f"\nResult {i+1}:\n{r}")

def generate_answer(query):
    # Step 1: retrieve relevant context
    context = retrieve(query, k=3)

    # Step 2: build prompt
    prompt = f"""
You are a helpful AI assistant.

Use the context below to answer the question.

Context:
{chr(10).join(context)}

Question:
{query}

Answer clearly and concisely:
"""

    return prompt

query = "What is RAG in machine learning?"

print(generate_answer(query))

chat_history = []

def chat(query):
    # retrieve context
    context = retrieve(query, k=3)

    # build prompt with memory
    history_text = "\n".join(chat_history[-4:])  # last 2 exchanges

    prompt = f"""
You are a helpful AI assistant.

Conversation history:
{history_text}

Context:
{chr(10).join(context)}

User: {query}
Assistant:
"""

    # store conversation
    chat_history.append(f"User: {query}")
    chat_history.append(f"Assistant: (generated using context)")

    return prompt

print(chat("What is RAG?"))
print(chat("Why is it useful in AI systems?"))

!pip install -q streamlit

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import numpy as np
# from sentence_transformers import SentenceTransformer
# import faiss
# 
# # -----------------------------
# # Sample knowledge base
# # -----------------------------
# documents = [
#     "Machine learning enables systems to learn from data.",
#     "Deep learning uses neural networks with many layers.",
#     "RAG combines retrieval with language models.",
#     "Vector databases store embeddings for similarity search."
# ]
# 
# # -----------------------------
# # Load embedding model
# # -----------------------------
# model = SentenceTransformer("all-MiniLM-L6-v2")
# 
# # -----------------------------
# # Build FAISS index
# # -----------------------------
# chunks = documents
# embeddings = model.encode(chunks).astype("float32")
# 
# index = faiss.IndexFlatL2(embeddings.shape[1])
# index.add(embeddings)
# 
# # -----------------------------
# # Retrieval function
# # -----------------------------
# def retrieve(query, k=2):
#     q_emb = model.encode([query]).astype("float32")
#     _, idx = index.search(q_emb, k)
#     return [chunks[i] for i in idx[0]]
# 
# # -----------------------------
# # Streamlit UI
# # -----------------------------
# st.title("RAG Chatbot")
# 
# query = st.text_input("Ask a question:")
# 
# if query:
#     context = retrieve(query)
# 
#     st.subheader("Retrieved Context")
#     for c in context:
#         st.write("-", c)
# 
#     st.subheader("Answer (Simulated LLM)")
#     st.write("Based on retrieved context:", context[0])

!pip install -q streamlit

!streamlit run app.py --server.port 8501 --server.address 0.0.0.0