# -*- coding: utf-8 -*-
"""Scikit-learn Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12zQ2R6Or4n24luwGIA1bzGsawaSZchIe

**Step 1: Importing Dataset**
"""

import kagglehub

path = kagglehub.dataset_download("blastchar/telco-customer-churn")

"""**Locate and load the CSV file**"""

import os

# list files inside downloaded folder
files = os.listdir(path)
print(files)

"""**Now load dataset**"""

import pandas as pd

df = pd.read_csv(os.path.join(path, files[0]))

print(df.shape)
df.head()

"""**Step 2: Data Cleaning + Target Encoding**"""

# 1. Drop customerID (not useful for prediction)
df = df.drop("customerID", axis=1)

# 2. Fix TotalCharges (it is stored as string with some blanks)
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

# 3. Fill missing values (created from coercion)
df["TotalCharges"] = df["TotalCharges"].fillna(df["TotalCharges"].median())

# 4. Convert target variable to binary
df["Churn"] = df["Churn"].map({"Yes": 1, "No": 0})

print("Data cleaned ✅")
df.head()

"""**Step 3: Train/Test Split**"""

from sklearn.model_selection import train_test_split

# Separate features and target
X = df.drop("Churn", axis=1)
y = df["Churn"]

# Split dataset
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y   # important for class balance
)

print("Train shape:", X_train.shape)
print("Test shape:", X_test.shape)

"""**Step 4: Build Preprocessing Pipeline**"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

# Identify feature types
numeric_features = X_train.select_dtypes(include=["int64", "float64"]).columns
categorical_features = X_train.select_dtypes(include=["object"]).columns

# Create transformers
numeric_transformer = StandardScaler()
categorical_transformer = OneHotEncoder(handle_unknown="ignore")

# Combine into ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ("num", numeric_transformer, numeric_features),
        ("cat", categorical_transformer, categorical_features)
    ]
)

print("Preprocessing pipeline ready ✅")

"""**Step 5: Build ML Pipeline (Logistic Regression + Random Forest)**"""

from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

# Model 1: Logistic Regression
log_reg_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", LogisticRegression(max_iter=1000))
])

# Model 2: Random Forest
rf_pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestClassifier(n_estimators=100, random_state=42))
])

print("Pipelines created successfully ✅")

"""**Step 6: Train Models**"""

# Train Logistic Regression
log_reg_pipeline.fit(X_train, y_train)

# Train Random Forest
rf_pipeline.fit(X_train, y_train)

print("Both models trained successfully ✅")

"""**Step 7: Model Evaluation**"""

from sklearn.metrics import accuracy_score, classification_report

# Predictions
log_pred = log_reg_pipeline.predict(X_test)
rf_pred = rf_pipeline.predict(X_test)

# Accuracy scores
log_acc = accuracy_score(y_test, log_pred)
rf_acc = accuracy_score(y_test, rf_pred)

print("Logistic Regression Accuracy:", log_acc)
print("Random Forest Accuracy:", rf_acc)

print("\n--- Logistic Regression Report ---")
print(classification_report(y_test, log_pred))

print("\n--- Random Forest Report ---")
print(classification_report(y_test, rf_pred))

"""**Step 8: Hyperparameter Tuning (GridSearchCV)**"""

from sklearn.model_selection import GridSearchCV

param_grid = {
    "model__n_estimators": [100, 200],
    "model__max_depth": [None, 10, 20],
    "model__min_samples_split": [2, 5]
}

grid_search = GridSearchCV(
    estimator=rf_pipeline,
    param_grid=param_grid,
    cv=3,
    scoring="accuracy",
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best CV Score:", grid_search.best_score_)

"""**Step 9: Final Evaluation (Best Model)**"""

from sklearn.metrics import accuracy_score, classification_report

# Best model from GridSearchCV
best_model = grid_search.best_estimator_

# Predictions
y_pred = best_model.predict(X_test)

# Accuracy
acc = accuracy_score(y_test, y_pred)
print("Final Model Accuracy:", acc)

# Detailed report
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred))

import joblib

joblib.dump(best_model, "churn_pipeline.pkl")

print("Model saved successfully ✅")

